### ISSUE TITLE
FR: [UI] group connection options

### ISSUE THREAD

**Issue by LecrisUT** [ReceiptManager/receipt-manager-app#17]
Group the different possible connection settings, and have a dropdown/radio buttons to choose which settings to use. So far the options are:
- zeroconf scanning the local network
- manual IP/Port
- domain-name
- HTTPS on/off
Ideally the domain-name and manual IP/Port should be one option, and then https can be inferred from the URL.

**Comment by monolidth** [comment]
See: cd318c74d02a53004922926e39833ec07c9797db

I simplify the network interface the following. 

Only one TextField for both (ipv4 address or domain).

1. Check via regex if the given server address is an ipv4 address or a domain
2. Move network related options in one settings tile

Regards,

William
