### ISSUE TITLE
FR: Fine camera controlls

### ISSUE THREAD

**Issue by LecrisUT** [ReceiptManager/receipt-manager-app#18]
Would be more useful if we can manually adjust the focus and exposure of the camera. Otherwise you can get overexposed white paper. Sometimes there is a document settings on the camera app, but I'm not sure if it's the app or if it can be used externally.

**Comment by monolidth** [comment]
Manuell focus is at the moment not possible. All flutter camera libraries do not support manual focus. Thus, I implement edge detection. You can see the result [here](https://imgur.com/a/RfbJb4n).

I appreciate feedback!

Regards,
William

**Comment by LecrisUT** [comment]
Great addition. Wonder how it behaves with crumbled up receipts. Just curious, no need to implement anything there for now.

I should show you how it behaves on my end (Android 10 AOSP), and why some exposure/focus control is needed.

https://user-images.githubusercontent.com/25577083/112773140-cec94a80-906f-11eb-8fc1-abace3412117.mp4

**Comment by monolidth** [comment]
> Great addition. Wonder how it behaves with crumbled up receipts. Just curious, no need to implement anything there for now.

Well, it depend how crumbled the receipt are. 


> I should show you how it behaves on my end (Android 10 AOSP), and why some exposure/focus control is needed.

Looks like a weird bug. I never faced this issue before. I take a look at the camera issue page.


Regards,

William

**Comment by monolidth** [comment]
I published receipt manager app `1.1.3`. You can try the edge detector and see if this issue still appear (since the edge detector does not use the camera library)

https://github.com/ReceiptManager/receipt-manager-app/releases/tag/1.1.3

Regards,

William

**Comment by LecrisUT** [comment]
Good news, bad news. I think it was the updated dependencies, now the pictures are no longer overexposed. However the edge detection does not process for me. It tries to pick up random elements on the side. Tried with contrasting colors for the receipt and background, but it still didn't catch anything.

If possible you should pick up the object at the centered in the camera as the receipt and try to process the edges from there.

**Comment by monolidth** [comment]
> Good news, bad news. I think it was the updated dependencies, now the pictures are no longer overexposed. 

Sounds good, but now the scaling does not work for me :)

> Tied with contrasting colors for the receipt and background, but it still didn't catch anything.

I would be happy to get the logcat output. Maybe the edge detector crashes (and you don't even noticed). If not try to increase the distance. Sometimes I'm facing this bug too.

**Comment by monolidth** [comment]
> I got the edge detection to work, but it seems to be sensitive to lighting and background

Great news. I guess a solution is to use specific parameters depending on brightness.

The edge detector works well if it is contrasty. However, due to performed transformations, non-contrasty backgrounds are very hard to detect.

> Is it when it's not an appropriate aspect ratio it crops out part of the receipt? Because that's what I see happening.

Using edge detection or without? For me, no part of the receipt is cropped out but there is an empty white space now.

> With enable debug output, I don't think I see the full log. You should add an option to save and retrieve the log. If there's a standard android way of doing it also let me know.

Since at least something appear on the screen, there is no crash. I will adjust the parameters and check if it works.

**Comment by monolidth** [comment]
Implemented, see dev branch.

**Comment by LecrisUT** [comment]
This is will take some work, but can you implement a CI/CD, like Travis, Jenkins or TeamCity? Both for nightly builds and pull requests, but also for creating releases and pre-releases and publishing them on fdroid

**Comment by monolidth** [comment]
Good idea, I will work on that, at the moment the remote builds fail, since I use a local library.

**Comment by monolidth** [comment]
![Bildschirmfoto vom 2021-04-15 12-42-02](https://user-images.githubusercontent.com/71930307/114856987-08c47b80-9de8-11eb-9530-0370014791ce.png)

Some notes:
I completely rewrite the application and I use the clean code architecture and null safety because it is easier to maintain and develop. I remove all redundant code and improve the code quality.

Some new features are:
* support a file picker and a gallery picker (therefore no image cache is required)
* typesafe form
* cleaner look with splash screen
* better database scheme
* steam and future builder with loading animations for completion

However, there are still some bugs in this release due null safety migration. Therefore, I see no point to push a new release.

Regards,
William

**Comment by LecrisUT** [comment]
Sounds like good coding practices :).
> However, there are still some bugs in this release due null safety migration. Therefore, I see no point to push a new release.

Agree, and usually the CI/CD will only push a release on version change, and pre-release on RC version increment, so you don't need to worry about that aspect.

By clean code architecture, you mean no documentation comments in the code? There are some tools like `CodeStream` that can help keep track of comments inside the code without putting it in code comment or repository. It is mostly for team development, but works for single developer environment as well.

> - cleaner look with splash screen

Splash screen on start-up? If possible I would suggest against that. It gets old and feels slow very quickly. Having a snappy feeling from the landing page goes a long way for the user. The simpler the home-page the faster it will load and it would have a cleaner feeling. I believe most packages can be loaded post initialization and in the background.

Some other notes, you can setup `git-lfs` to track non-code files like `.png` and so on. That should make the `.git` folder more manageable.

**Comment by monolidth** [comment]
> By clean code architecture, you mean no documentation comments in the code? There are some tools like CodeStream that can help keep track of comments inside the code without putting it in code comment or repository. It is mostly for team development, but works for single developer environment as well.

No, I was referring to: https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html

> Splash screen on start-up? If possible I would suggest against that. It gets old and feels slow very quickly. Having a snappy feeling from the landing page goes a long way for the user. 

Agree, but this is only necessary for the first initialization e.g.

* initialize controllers, language strings and shared preferences
* load main page

which means that the app still feel snappy and the new version outperform the older versions. 

> Some other notes, you can setup git-lfs to track non-code files like .png and so on. That should make the .git folder more manageable.

 Thank you, that is what I'm searching for a long period of time without even knowing.
