### ISSUE TITLE
FR: Admin store names from app

### ISSUE THREAD

**Issue by LecrisUT** [ReceiptManager/receipt-manager-app#20]
Would be more applicable to add and manage the store names on the app rather than the server as they will change with time. In the future these can also be synced/imported from Grocy.

**Comment by monolidth** [comment]
Do you mean to manage the store names in the config.yml?

**Comment by LecrisUT** [comment]
Yes, those ones. Alternative a front-end can be provided, but just for this integration, it can be postponed for when more features are introduced.
