### ISSUE TITLE
Real-life receipt parsing issues

### ISSUE THREAD

**Issue by LecrisUT** [ReceiptManager/receipt-manager-app#21]
Would be helpful to keep track of some common real-life receipt issues. Although It might be better as a Github issues so each issue can have its own thread to discuss on.
- [x] Edge detection is sensitive to lighting and background contrast (e.g. pure white receipt on grey or coloured desk is not detected)
- [x] Cropping the receipt cuts off part of it
- [ ] Detection on non-latin alphabet? (to be tested)
- [ ] Receipts can be badly crumbled? (to be tested)
- [ ] Receipts will generally be curved? (to be tested)
- [ ] Some receipts are coloured: e.g. credit card or train ticket ones. Since those are more niche usecases and have no item information it can be ignored for now.
- [ ] East Asian receipts are very packed both in design and character design so it can be sensitive to focus, blur and grey-scaling.

**Comment by monolidth** [comment]
Great ideas and I agree with all of them and I try my best :)

**Comment by monolidth** [comment]
Update, I tried different methods and parameters e.g. I tried to use the [otsu method](https://en.wikipedia.org/wiki/Otsu%27s_method) to calculate the best threshold but with no success, maybe this is not so trivial :)
