### ISSUE TITLE
Wiki typo correction and question on what information is supposed to be stored

### ISSUE THREAD

**Issue by JavaJeremy** [ReceiptManager/receipt-manager-app#25]
I checked out this wiki section for [How it works](https://github.com/ReceiptManager/receipt-manager-app/wiki/How-it-works) and found some typos 
\- unfortunately [GitHub doesn't support pull request for these wikis yet](https://stackoverflow.com/q/10642928) :(
Here's my corrected version (and I'd probably shorten "application" to "app"):

1. The user takes a photo of a receipt
2. The application uploads the receipt to the server
3. The server parses the receipt and sends the output (as json response) back to the application
4. The application stores the receipt in a SQL database

What I'm missing here is information about which properties of the receipt are saved.
Since it's not specified I assumed all - including each individual product and price - but then I read your medium article and noticed that just the key properties are saved. I also noticed that nothing happens when I press on a saved receipt in the "Expenses overview" so I assumed the app's not meant for that "drill-down".
Maybe in order to make this more clear, point 3 could be changed to something like this:
3. The server tries to parse the receipt (date, total, store name) and sends the output (as json response) back to the application

On the other hand I just noticed the property "receiptItems" in [receipt_server.py](https://github.com/ReceiptManager/receipt-parser-server/blob/master/src/receipt_server.py). So I'm assuming that you did already think about including the individual products but didn't implement that feature yet due to missing time...but I don't know :D

**Comment by monolidth** [comment]
Thanks for the work. I will disable the wiki shortly and move remaining parts to the readTheDocs wiki because it has more features and a better structure.

Yes, I already implement this feature. You have to enable the feature first. Go to Settings / Developer Settings / Show items.

I refactor the app at the moment. Otherwise I would have added a database fuzzy searcher to improve the parser.

**Comment by JavaJeremy** [comment]
Great to hear that such big improvements are already on the way - thanks!
I will try out the `Show articles` option (because I can't find `Show items` in the app) and this issue can be closed once the doc moving is done, I guess 👍

**Comment by monolidth** [comment]
Done, see `dev` branch
