### ISSUE TITLE
1.1.6 adds non-free dependencies

### ISSUE THREAD

**Issue by IzzySoft** [ReceiptManager/receipt-manager-app#30]
My updater just sent me a warning: the new v1.1.6 introduces some proprietary components requiring the AntiFeatures `NonFreeNet` and `NonFreeDep` with my repo – while being a show-stopper for inclusion with F-Droid.org should you have planned that:

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
```

Was that intended – or accidentally dragged in by some dependency? In the first case I'd ask you to reconsider: proprietary components taint your app, it's no longer entirely FOSS now. In both cases I kindly ask you to get rid of those libs again. Until then, I'll have to flag your app with the two mentioned AntiFeatures – and the :star: in my app-listings will be lost automatically. The "before-state" will be restored once those libraries are gone again.

As your app deals with sensitive data (finances), this combination further is a show-stopper for my repo as well. So should the move have been intentionally, and you want to stick to it, I'll have to remove your app from my repo unfortunately :cry:

My guess is this is for "upload notifications" mentioned with the release notes – as I see the app now requests the C2D permission. May I suggest taking a look [here for alternatives](https://gitlab.com/-/snippets/1896503#push)? You could instead use [UnifiedPush](https://unifiedpush.org/) – which supports multiple notification systems including FCM but, to my knowledge, not require using proprietary libraries in your app.

**Comment by IzzySoft** [comment]
PS: For now I've reset your app in my repo to v1.1.5 and disabled auto-update until this issue is solved, thus avoiding the AntiFeatures and giving you time to find/implement a solution. The app description will mention this and link here for details.

**Comment by monolidth** [comment]
> My updater just sent me a warning: the new v1.1.6 introduces some proprietary components requiring the AntiFeatures NonFreeNet and NonFreeDep with my repo – while being a show-stopper for inclusion with F-Droid.org should you have planned that:

You are right! I added the awesome notification library and it looks that this library has build-in firebase support. 

Thus, I never use it. Instead, I use this library to generate local notifications.  I will remove this library but I have to refactor the code again. Again, the main issue is that there, not notification libraries at the moment.

> As your app deals with sensitive data (finances), this combination further is a show-stopper for my repo as well. So should the move have been intentionally, and you want to stick to it, I'll have to remove your app from my repo unfortunately cry

As I mentioned, I never share data to any third party (see explanation above)

> PS: For now I've reset your app in my repo to v1.1.5 and disabled auto-update until this issue is solved, thus avoiding the AntiFeatures and giving you time to find/implement a solution. The app description will mention this and link here for details. 

Thank you, I'm good with that.

**Comment by IzzySoft** [comment]
Thanks for your reply! And good to know that you don't share data to 3rd parties. Problem is, as you certainly understand: those libraries show up, as well as the corresponding C2DM permission. As FCM is proprietary, only their developers can say what it really does – so even if you don't use it intentionally, it might "do things" nevertheless. Which is why this combination is so dangerous – why I don't permit that in my repo and why F-Droid won't permit any proprietary stuff at all.

I'm relieved you already have a path-of-action in mind. I understand that refactoring cannot happen "overnight" of course. So I'm looking forward to your "ping" here to re-enable updates as soon as I can. Thanks a lot!

**Comment by IzzySoft** [comment]
> Again, the main issue is that there, not notification libraries at the moment.

Depends:

* [Android-AppMsg](https://github.com/johnkil/Android-AppMsg) offers In-layout notifications (but is quite aged) – oops, Java, you need Flutter
* [flutter_local_notifications](https://github.com/MaikuB/flutter_local_notifications) maybe?

**Comment by monolidth** [comment]
Totally agree with all. I will keep this open until it is fixed.

**Comment by monolidth** [comment]
I will take a look at the flutter local notification library. Thank you!

**Comment by IzzySoft** [comment]
I've not checked it thoroughly (I'm no Flutter dev aftger all), was just going by name and description. Not sure what dependencies it might ship :scream:

**Comment by monolidth** [comment]
Should be resolved!

**Comment by IzzySoft** [comment]
Thanks for letting me know! As there's no new tag (yet): where can I find the APK to check?

**Comment by monolidth** [comment]
Sorry, I forgot to update the binary 😅

**Comment by monolidth** [comment]
I'm still uploading :)

**Comment by monolidth** [comment]
See version 1.1.7

**Comment by IzzySoft** [comment]
Thanks! Confirmed: all green again, re-activating auto-updates. v1.1.7 should show up with the next sync in about 9h (already pulled that manually for checking).

As this solves the problem, I'm closing the issue. Thanks for your prompt help!
